### ISSUE TITLE
Expand functionality of geometry classes in djutils-draw

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#1]
In djutils-draw, some of the classes lack easy access methods such as getting the points of a geometry as a list or array -- only an iterator version exists. This has to be extended to avoid rewriting the same code over and over again. Alternative implementations for the constructors are missing (or static builders / create methods). getters to common data types are missing for many of the drawing primitives. 

Many of the methods are available in the OpenTrafficSim project, and they could be moved from OTS to djutils-draw. OTS is already dependent on djutils, so having all classes and methods in one place instead of maintaining two sets of largely overlapping code (OtsPoint3D and Point3d, OtsLine3D and Line3d, Bounds and Bounds3d, OtsShape and Polygon2d, etc.) will make life a lot easier.

Of course, unit tests are important for all new code, especially since test coverage is already very good.

**Comment by OTSim** [comment]
Added ArrayList getter as constructing an array appeared really complicated.
The meaning of disjoint and (consequently) intersect has changed. This may have some repercussions elsewhere...
