### ISSUE TITLE
Check maximum angle on Bezier

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils#12]
`Bezier` has `// TODO check angles` for both 2D and 3D. The methods with these TODO's have a loop that checks whether between two current points, an extra point is required to be within the limit of precision in terms of distance. In each step there are 3 points: _prev_, _median_, and _next_. Derivatives at _prev_ and _end_ can be derived using https://pomax.github.io/bezierinfo/#derivatives. Then, the absolute tangent change between them can be compared to a threshold. If the change is too large, the median point can be inserted.

The derivative is calculated as:
- The original Bezier has _i_ = 1 ... _n_ control points _P<sub>i</sub>_.
- The derivative Bezier has _j_ = 1... _n_ - 1 control points _G<sub>j</sub>_.
- Each of those control points is calculated as: _G<sub>j</sub>_ = (_n_ - 1)*(_P<sub>j+1</sub>_ - _P_<sub>_j_</sub>).
- Using the _t_ value of the original Bezier on the derivative Bezier gives _x_' and _y_' of the original curve at _t_.
- The resulting tangent direction is calculated as _atan2_(_y_', _x_').

**Comment by Peter-Knoppers** [comment]
No longer an issue as we now have continuous Beziers that totally replace the earlier Beziers.
