### ISSUE TITLE
CliUtil default decimal values and Locale

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils#13]
Suppose a class (program) has the following command line argument:
```java
    @Option(names = "--acceptedGap", description = "Accepted gap.", defaultValue = "0.5s")
    private Duration acceptedGap;
```
The resulting value (when no command line argument is given and hence the default value should be used) will actually depend on the `Locale`. In particular:

`Locale.setDefault(Locale.Category.FORMAT, Locale.US);` results in **0.5s**.
`Locale.setDefault(Locale.Category.FORMAT, Locale.GERMAN);` results in **5.0s**.
When `System.out.println(Locale.getDefault(Locale.Category.FORMAT));` prints `nl_NL`, this results in **5.0s**.
Although `Locale.setDefault(Locale.Category.FORMAT, new Locale("nl_NL"));` results in **0.5s**.
`Locale.setDefault(Locale.Category.FORMAT, Locale.FRANCE);` results in **0.0s**.

This issue can be circumvented by using:

```java
    @Option(names = "--acceptedGap", description = "Accepted gap.")
    private Duration acceptedGap = Duration.instantiateSI(0.5);
```
But this form of using default values has [limitations elsewhere](https://picocli.info/#_field_values).

This issue only occurs with DJUNITS properties. For e.g. a `double` the default value works fine.

**Comment by WJSchakel** [comment]
I see two options to solve this issue:

1) Force use of `Locale.US` for default values. DJUNITS does not support this directly in the `valueOf(String)` methods, but that will use a `NumberFormat` which uses `Locale.getDefault(Locale.Category.FORMAT)`. Therefore, `CliUtil` could set `Locale.setDefault(Locale.Category.FORMAT, Locale.US);` in the `execute()` method just before the line `ParseResult parseResult = commandLine.parseArgs(args);`. It must also reset the value.

2) Forward a `Locale` to the `CliUtil.execute()` method, and use it in the same way.

In theory, other code could change the `Locale` during the call to `parseArgs()`. But the scope of this code is limited and involves custom converters found in `CliUnitConverters`.

**Comment by averbraeck** [comment]
Solved with a mixin class with options in `CliUtil.execute(...)`:

```java
    /** Mixin class to provide a --locale option, and a default locale. */
    static class InitLocale
    {
        /** the locale. */
        @Option(names = {"--locale"}, defaultValue = "en-US", description = "locale for variables with units.")
        private String locale;

        /**
         * @return the locale from --locale
         */
        String getLocale()
        {
            return this.locale;
        }
    }
```

The mixin class is added at the start of the `execute(...) method:

```java
        var initLocale = new InitLocale();
        commandLine.addMixin("locale", initLocale);
```

Then, before the parsing in `execute(...)`, a first-pass parsing takes place without collecting errors. The old locale is saved:

```java
        Locale saveLocale = Locale.getDefault();
        commandLine.getCommandSpec().parser().collectErrors(false);
        commandLine.parseArgs(args);
        Locale.setDefault(Locale.forLanguageTag(initLocale.getLocale()));
```

After parsing, the locale is reset to what it was:

```java
        Locale.setDefault(saveLocale);
```

This solves the issue, and adds a default `--locale` option to the `CliUtil` class.

**Comment by averbraeck** [comment]
Code like this now runs fine:

```java
        locale = new Locale("nl", "NL");
        Locale.setDefault(locale);
        args = new String[] {"--duration", "0.5s"}; // note that en_US is ALWAYS the default
        CliUtil.execute(options, args);
        assertEquals(new Duration(0.5, DurationUnit.SECOND), options.getDuration());
        args = new String[] {"--duration", "0,5s", "--locale", "nl"};
        CliUtil.execute(options, args);
        assertEquals(new Duration(0.5, DurationUnit.SECOND), options.getDuration());
        args = new String[] {"--duration", "0,5s", "--locale", "nl_NL"};
        CliUtil.execute(options, args);
        assertEquals(new Duration(0.5, DurationUnit.SECOND), options.getDuration());
        assertEquals(locale, Locale.getDefault());
```

Note that when **no --locale parameter has been set**, the language used to parse is **always US-English**.

**Comment by averbraeck** [comment]
The locale in the program that has been set before `CliUtil.execute` is called is preserved by the program.

**Comment by averbraeck** [comment]
It turns out the separator between language and country is not standardized. It could either be "-" or "_"... Java traditionally uses an underscore, but officially, a hyphen is used (https://en.wikipedia.org/wiki/IETF_language_tag). Therefore, the code has been changed as follows:

```java
        String[] localeParts = retrieveLocale.getLocale().contains("_") 
                ? retrieveLocale.getLocale().split("_")
                : retrieveLocale.getLocale().split("-");
        if (localeParts.length == 1)
        {
            Locale.setDefault(new Locale(localeParts[0]));
        }
        else if (localeParts.length == 2)
        {
            Locale.setDefault(new Locale(localeParts[0], localeParts[1]));
        }
        else
        {
            Locale.setDefault(new Locale(localeParts[0], localeParts[1], localeParts[2]));
        }
```

**Comment by averbraeck** [comment]
Furthermore, the mixin has some problems with errors -- no language is set when a unit-value cannot be parsed with the wrong language. Therefore, a 2-pass parsing is performed. First, the cli-parser tests against these options:

```java
    static class RetrieveLocale
    {
        @Option(names = {"--locale"}, defaultValue = "en-US", description = "locale for variables with units.")
        private String locale;

        String getLocale()  { return this.locale; }

        @Unmatched
        private List<String> remainder;
    }
```

using the code:

```java
        Locale saveLocale = Locale.getDefault();
        RetrieveLocale retrieveLocale = new RetrieveLocale();
        CommandLine cmdLocale = new CommandLine(retrieveLocale);
        cmdLocale.parseArgs(args);
```

Only **after this**, the code with the mixin and the same `--locale` argument is executed. This solves all problems.

**Comment by averbraeck** [comment]
The code now successfully parses the following arguments for a duration:

```java
args = new String[] {"--duration", "0.5s"};
args = new String[] {"--duration", "0.5s", "--locale", "en"};
args = new String[] {"--duration", "2h", "--locale", "en"};
args = new String[] {"--duration", "0.5s", "--locale", "en_US"};
args = new String[] {"--duration", "0.5s", "--locale", "en-US"};
args = new String[] {"--duration", "0,5s", "--locale", "nl"};
args = new String[] {"--duration", "2uur", "--locale", "nl"};
args = new String[] {"--duration", "0,5s", "--locale", "nl_NL"};
args = new String[] {"--duration", "0,5s", "--locale", "nl-NL"};
args = new String[] {"--duration", "0,5s", "--locale", "de-DE"};
args = new String[] {"--duration", "0,5s", "--locale", "no-NO-NY"};
```

The unit test `TestCliLocale` tests these option and some others.

**Comment by averbraeck** [comment]
Errors are properly provided. When a unit does not exist, e.g., after providing a duration like:

```java
args = new String[] {"--duration", "2uukr", "--locale", "nl"};
```

the following error is shown on the console (and the program exits):

```
Invalid value for option '--duration': cannot convert '2uukr' to Duration 
   (java.lang.IllegalArgumentException: Error parsing Duration from 2uukr using Locale nl)
```

It does provide the locale used, and the argument for which the error was thrown (handy when many arguments are passed on the command line).

**Comment by averbraeck** [comment]
Completed as specified.
