### ISSUE TITLE
Polygon2d.contains() returns false for a clearly true result

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils#15]
For a polygon with 4 points as shown below, the point `(1,-3)` is given as *not* contained.
```
                                          (1000,1)
(0, -1)
         (1,-3)---->                      (1000,-3)
(0,-5)
```
For each line segment, the method checks whether it intersects with a line from the point that is tested towards the right (`---->`). This is tested using 4 conditions:
1. `y >= Math.min(prevPointY, curPointY)`
2. `y <= Math.max(prevPointY, curPointY)`
3. `x <= Math.max(prevPointX, curPointX)`
4. `prevPointY != curPointY`

Condition 3 checks that the intersection is indeed of a line towards the right. The 4th conditions checks that the intersected line segment is not on the line towards the right. The first two conditions check for an intersection solely by y-coordinates (which is possible due to the horizontal line we check).

The first two conditions will hold true for two consecutive line segments if the shared point by the line segments is where the intersections are found. This happens in the example, at exactly y = -3. The intersection counter is thus increased by 2, while there is actually only 1 intersection. In my estimation, this would be solved if '=' is removed from either condition.

This issue was revealed by `LaneTest.contourTest()` in OTS.

**Comment by Peter-Knoppers** [comment]
Found the cause. There was a "<=" in the contains code that should have been a "<". Added a unit test for this issue to ensure that we can't accidentally re-recreate this bug.
