### ISSUE TITLE
Drawable should implement Iterable<? extends P>

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#20]
The class `org.djutils.draw.Drawable<P extends Point<P>>` in djutils-draw implements an `Iterator<? extends P> getPoints()`, but the class itself does not implement `Iterable<? extends P>`, so it cannot be used in an enhanced for-loop. The suggestion is to implement `Iterator<? extends P> getPoints()` for this class.

**Comment by Peter-Knoppers** [comment]
I don't understand. You wrote:
Drawable implements
        Iterator<? extends P> getPoints()
and then the request is to implement
        Iterator<? extends P> getPoints()
???

**Comment by WJSchakel** [comment]
It should be possible to use:

```java
for (Point p : drawable)
{
}
```

Therefore the interface `Drawable` should be as:

`public interface Drawable<P extends Point<P>> extends Serializable, Iterable<P>`

Then the `iterator()` method should return the same result as `getPoints()`.

The `Iterator<? extends P> getPoints()` in the last sentence is inaccurate but is meant to mean the above.

**Comment by Peter-Knoppers** [comment]
Implemented. Removed the getPoints methods.
