### ISSUE TITLE
Improve documentation for Ray and OrientedPoint

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#23]
The classes `Ray` (`Ray2d` and `Ray3d`) and `DirectedPoint` (`DirectedPoint2d` and `DirectedPoint3d`) seem to store the exact same information, yet the two classes are very different. Explain in the Javadoc, and in the documentation why both classes exist.

**Comment by Peter-Knoppers** [comment]
In 2D the difference is the naming convention of the rotZ (vs phi). Class OrientedPoint2d has been removed.
