### ISSUE TITLE
Eval > RetrieveValue > Eval nested dependency not supported

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils#27]
The following code results in an exception on the last line.

```java
    public static void main(final String[] args)
    {
        Eval eval = new Eval();
        Map<String, Object> map = Map.of("param1", "{param2}", "param2", Dimensionless.instantiateSI(0.3));
        eval.setRetrieveValue(new RetrieveValue()
        {
            @Override
            public Object lookup(final String name)
            {
                Object value = map.get(name);
                if (value instanceof String && value.toString().startsWith("{"))
                {
                    return eval.evaluate(value.toString().substring(1, value.toString().length() - 1));
                }
                return value;
            }
        });
        System.out.println(eval.evaluate("1.0 - param2")); // 0,70000000
        System.out.println(eval.evaluate("1.0 - param1")); // RuntimeException: Stack empty at position 6
    }
```

The evaluator evaluates `1.0 - param1` and asks the `RetrieveValue` for `param1`. That instances sees a value of `{param2}`, and evaluates the content `param2` with the evaluator. That successfully results in `0.3`. But when the evaluator wants to perform the subtraction, the stack was cleared by the secondary use of the evaluator by the `RetrieveValue`. Note that the evaluator calls `this.stack.clear()` when starting to evaluate an expression.

Three solutions:
1. Throw an `IllegalStateException` in `Eval.evaluateExpression()` when a `boolean nested = true`, that the method itself sets `true` during a call to the evaluator.
2. When `boolean nested = true` create a copy of the `Eval` itself (which itself has `boolean nested = false`) using the same functions, `RetrieveValue`, etc. Forward the evaluation to the new instance and return it.
3. Do not clear the stack upon start of an evaluation. (Or only clear it if `boolean nested = false`.)

I think it should be solution 2. Solution 1 will prevent any form of nested dependency. Solution 3 is likely not even a solution as the stack may become in a wrong state with complicated nested calls, although we might try.

**Comment by OTSim** [comment]
Not a bug. This is very similar to a ConcurrentModificationException that you might get when modifying a Collection while iterating over it. The Eval code was not written with re-entrancy in mind. If you want to evaluate an expression while another expression is being evaluated, you can (and should) create another Eval instance.

**Comment by WJSchakel** [comment]
Than it should throw a clear exception to indicate this (solution 1). For OTS input parameters that depend on each other, some elaborate checking and copying will be needed (on OTS side).

**Comment by OTSim** [comment]
Detecting this problem and throwing an exception when things are about to go wrong makes good sense.
Does anyone have a suggestion for the exception that shall be thrown if this is about to happen? ConcurrentModificationException?
To avoid the exception from ever occurring, any evaluations that happen inside a RetrieveValue.lookup operation should take place in a separate Eval instance.

**Comment by averbraeck** [comment]
`ConcurrentModificationException` would indeed be a nice one. The Javadoc of the exception states that a `ConcurrentModificationException` is not necessarily throws as a result of multiple threads accessing and changing an object: "If a single thread issues a sequence of method invocations that violates the contract of an object, the object may throw this exception." So, in my opinion, it would be an exception that describes the situation well.

**Comment by OTSim** [comment]
This may be solvable without a `ConcurrentModificationException` by saving the evaluator state on entry of evaluate and restoring that state on (any) return. This may require a try-finally construct.
