### ISSUE TITLE
PolyLine.getLocation(..) not intuitive

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#30]
The `PolyLine2d.getLocation(double)` method returns a `Ray2d`, where the word 'location' suggests the return of a `Point2d` or an extension of a `Point2d` such as an `OrientedPoint2d`. Same for 3d. Sometimes a Ray is useful, sometimes a Point is useful. Both methods should be present, with clear names so users know what to expect. E,g., `Polyline2d.getOrientedPointAt(double)` and `Polyline2d.getRayAt(double)` or even `Polyline2d.getOrientedPointAtFraction(double)` and `Polyline2d.getRayAtFraction(double)`.

**Comment by Peter-Knoppers** [comment]
Things are quite confusing when the 3D version is concerned.
We may need to create a class DirectedPoint3d, extending Point3d (as does OrientedPoint3d). DirectedPoint3d adds phi and theta, while OrientedPoint3d adds dirX, dirY and dirZ. A Ray3d would extend a DirectedPoint3d. The main difference between a DirectedPoint3d and a Ray3d is the Bounds property.
In 2D, there is less need for a DirectedPoint2d class as there would be no essential difference between a DirectedPoint2d and an OrientedPoint2d (although we could name that added field dirZ in OrientedPoint2d and phi in DirectedPoint2d). The main reason to introduce DirectedPoint2d is naming consistency.
What shall we do?

**Comment by averbraeck** [comment]
A `DirectedPoint3d` is a point in a 3d space with a **direction vector**. The direction vector is in essence providing a rotation around the Y-axis and around Z-axis to provide a unique direction vector from (0, 0, 0), after which the point is translated to its (x, y, z) position. In essence, all points on a unit sphere around (0, 0, 0) can be reached when one of the two rotations is between 0 and two pi, and the other rotation is between 0 and pi (spherical coordinates). Note that a `DirectedPoint3d` is a directed vector **from a point**, not a spherical coordinate itself (a vector (r, dirY, dirZ) from the origin to a point) 

A `OrientedPoint3d` is a point that has a 3-dimensional **orientation**, This orientation is indicated by three rotation degrees of freedom, sometimes denoted as 'yaw, pitch and roll'. Think about a plane at location (x, y, z), where the plane can point more to the left or right from a top view (rotZ, or yaw), where the nose can be more up or down (e.g., rotY, or pitch), and where the plane can roll along its longitudinal axis (e.g., rotX, or roll). This is one degree of freedom more than the `DirectedPoint3d`, where the difference of 'roll', or `rotX` would not be visible; the vector would rotate along its axis, which would not make any difference.

**Comment by averbraeck** [comment]
A `Ray` is different from a `DirectedPoint` or an `OrientedPoint`. A `Ray` is, in a sense, a **directed** `LineSegment` and not a directed `Point` (!). That is also why the `Bounds` if a `Ray` return a half-space and not a point (a degenerate bounds where `minX = maxX`, `minY = maxY`, and `minZ = maxZ`). 

Since the coordinates of a `Ray` go to infinity, we cannot store the start point and end point, but have to store it as a start point and a direction. This **looks the same as a `DirectedPoint`, but it is a truly different concept**.

**Comment by averbraeck** [comment]
If the above descriptions make sense, we might add some of them to the Javadoc of the respective interfaces and classes to clarify our interpretation of the concepts in djutils-draw.

**Comment by Peter-Knoppers** [comment]
I think it (mostly) makes sense.
GetLocation & friends should return a DirectedPoint.
If we really need something that creates a Ray at a location, we can name that method getRayAt, or something similar.

For now, I would like to change the object returned by getLocation methods to a DirectedPoint.

**Comment by averbraeck** [comment]
For me, that makes perfect sense!

**Comment by WJSchakel** [comment]
Makes sense to me. Alternatively there could be `Ray2d = DirectedPoint2d.toRay()` and `DirectedPoint2d Ray2d.toDirectedPoint()` methods. They can even share the same information if one is implemented based on the other, i.e. something like:

```java
public class DirectedPoint2d implements Point<DirectedPoint2d>
{
    final double x;
    
    final double y;
    
    final double rotZ;
    
    private Ray2d ray = null;
    
    public DirectedPoint2d(final double x, final double y, final double rotZ)
    {
        this.x = x;
        this.y = y;
        this.rotZ = rotZ;
    }

    public Ray2d asRay()
    {
        if (this.ray == null)
        {
            this.ray = new Ray2d(this);
        }
        return this.ray;
    }
    
    public Bounds2d getBounds()
    {
        return new Bounds2d(this.x, this.x, this.y, this.y);
    }
}
```
And:
```java
public static class Ray2d implements Ray<Ray2d, DirectedPoint2d> 
{
    private final DirectedPoint2d point;
    
    Ray2d(final DirectedPoint2d point)
    {
        this.point = point;
    }

    public Ray2d(final double x, final double y, final double rotZ)
    {
        this.point = new DirectedPoint2d(x, y, rotZ);
    }

    public DirectedPoint2d asOrientedPoint()
    {
        return this.point;
    }
    
    public Bounds2d getBounds()
    {
        if (this.point.rotZ) > 0.5 * Math.PI)
        {
            return new Bounds2d(Double.NEGATIVE_INFINITY, this.point.x, this.point.y, Double.POSITIVE_INFINITY);
        }
        if (this.point.rotZ > 0.0)
        {
            return new Bounds2d(this.point.x, Double.POSITIVE_INFINITY, this.point.y, Double.POSITIVE_INFINITY);
        }
        if (this.point.rotZ < -0.5 * Math.PI)
        {
            return new Bounds2d(Double.NEGATIVE_INFINITY, this.point.x, Double.NEGATIVE_INFINITY, this.point.y);
        }
        return new Bounds2d(this.point.x, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY, this.point.y);
    }
}
```
