### ISSUE TITLE
Include range slider

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils#45]
Currently, we use a copy of a multislider implementation in some projects like OTS from quite some years ago, where differences are made between Windows XP and Windows Vista implementations. The code is for sure not current, and can be re-implemented. Several examples of a Swing multislider or a slider with lower and upper bound exist, being less dependent on specific OS versions for the styling and using pure Swing code.

**Comment by averbraeck** [comment]
One project with an MIT license we can learn from is https://github.com/ernieyu/Swing-range-slider. The project is explained at https://ernienotes.wordpress.com/2010/12/27/creating-a-java-swing-range-slider. @Peter-Knoppers  already asked whether the code could be freely used a couple of years ago, and the answer was 'yes'. The idea is to make an extension of this code to match the needs in projects like opentrafficim.

**Comment by averbraeck** [comment]
The question remains where to place the code for the range-slider, since djutils does not have a specific place for swing components. An idea would be to create a module djutils-swing where specific swing utilities can be stored.

**Comment by averbraeck** [comment]
I went for a completely different implementation than any of the previous implementations, e.g. those from https://www.javatips.net/api/Pixelitor-master/src/main/java/com/bric/swing/MultiThumbSlider.java or https://ernienotes.wordpress.com/2010/12/27/creating-a-java-swing-range-slider/ (with code in https://github.com/ernieyu/Swing-range-slider/tree/master/src/slider).

**Comment by averbraeck** [comment]
First working version of the `MultiSlider` (still some additions to be done):

![image](https://github.com/user-attachments/assets/cc5679ae-2266-4348-b0b3-c4a5d1d636a4)

The `MultiSlider` can be styled and given tick marks, labels, etc. It also automatically scales:

![image](https://github.com/user-attachments/assets/91fa8c1f-dcbb-4ad8-b123-cd2a60369b75)

**Comment by averbraeck** [comment]
The slider now correctly shows all the knobs on top -- the trick was to not show the track (the guardrails) for sliders 0 to n-1, and to show it for the last slider:

![image](https://github.com/user-attachments/assets/809e1ee1-8843-4281-85b7-1a20d985e906)

**Comment by averbraeck** [comment]
Vertical sliders also work:

![image](https://github.com/user-attachments/assets/0504b206-bc0d-4d81-9cc5-c2a6a12a0b0e)

**Comment by averbraeck** [comment]
With an UI Manager change, the opaque nature of the sliders disappears, and the mouse events are only caught by one slider:

![image](https://github.com/user-attachments/assets/6359f813-410f-4c38-a281-c85ad3d44288)

**Comment by averbraeck** [comment]
A state machine has been included to check that the same thumb will receive the mouse events when e.g., pressing and later releasing the mouse, or when the mouse is pressed, the mouse is dragged, and the mouse is released.

**Comment by averbraeck** [comment]
The demo has a built-in reset button to see if the `setValue(i, n)` function works, and if the sliders are indeed reset.

**Comment by averbraeck** [comment]
This is the current look-and-feel of the demo:

![image](https://github.com/user-attachments/assets/e3c2dd59-d7db-4a03-806c-867b3ae477b6)

**Comment by averbraeck** [comment]
Added an `int busySlider` and a `boolean busy` to the `MultiSlider` to indicate which of the underlying sliders is busy. The `busy` flag will be updated **before** the mouse action is carried out, so the `ChangeListener` can look at the `busy` flag to be only updated **after** an action has completed. This means that when the mouse is, e.g., dragging a thumb, we can check to only print the new values after the release of the mouse:

```java
        horSlider.addChangeListener(new ChangeListener()
        {
            @Override
            public void stateChanged(final ChangeEvent e)
            {
                MultiSlider s = (MultiSlider) e.getSource();
                for (int i = 0; i < s.getNumberOfThumbs(); i++)
                {
                    if (!s.isBusy())
                        System.out.println("Horizontal Thumb " + i + ": " + s.getValue(i));
                }
            }
        });
```

**Comment by averbraeck** [comment]
The basic multislider is working. Several additions will be made using separate issues.
