### ISSUE TITLE
Merge `Curve` and `Flattable`

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils#53]
In particular:
- `Curve2d` can include what is now in `OffsetFlattable2d`.
- `Curve3d` can include what is now in `Flattable3d`.

This will solve some ambiguity surrounding `Flattable.getLength()` (length of shape, or polyline?).

Methods `length()` and `getLength()` in `Bezier2d` and `Bezier3d` should not both be public, or one should be removed. The length should be cached upon first use as the computation is not cheap. It should NOT be calculated in the constructor, as then a cascade of lower-order Beziers required to calculate the length, will all calculate their length.

**Comment by Peter-Knoppers** [comment]
Completed
