### ISSUE TITLE
Make djutils-math project

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#58]
Several classes and functions in djutils-base and other djutils projects are purely math implementations. These can better be moved to a new djutils-math project.

**Comment by Peter-Knoppers** [comment]
If we're really going to implement algebraic operations, should we take a closer look at similar packages?
I fondly remember playing with muSimp & muMath on my Apple ][ clone computer (around 1980).
[The manual is in the Internet archive](https://archive.org/details/msmumath/MS_muMATH-muSIMP80-Manual/page/n5/mode/2up)

**Comment by averbraeck** [comment]
Documentation on readthedocs has also been adapted:

![image](https://github.com/user-attachments/assets/1cf7ebc3-fc00-4fcd-b26f-24ff907c8940)

**Comment by averbraeck** [comment]
> If we're really going to implement algebraic operations, should we take a closer look at similar packages? I fondly remember playing with muSimp & muMath on my Apple ][ clone computer (around 1980). [The manual is in the Internet archive](https://archive.org/details/msmumath/MS_muMATH-muSIMP80-Manual/page/n5/mode/2up)
> 
> [An overview of computer algebra systems can be found on Wikepedia: ](https://en.wikipedia.org/wiki/List_of_computer_algebra_systems)

@Peter-Knoppers : we might, but as of now, the math package is just the placeholder of our own math classes that were originally in the djutils-base project.

**Comment by averbraeck** [comment]
The shell scripts for djutils site generation on djutils.org should keep working, since they will automatically include the two new modules from the parent pom file.

**Comment by averbraeck** [comment]
Move looks like being finished. All unit tests work.
