### ISSUE TITLE
Domain range of ContinuousPiecewiseLinearFunction

### ISSUE THREAD

**Issue by Peter-Knoppers** [averbraeck/djutils#63]
Currently, the ContinuousPieceWiseLinearFunction limits domain values to the interval [0.0, 1.0]. This is well suited for catching errors in the original use of these functions (offset-functions for Arc, Bezier, and other Curves that are generated as a function of a t-value that runs from 0.0 to 1.0).

Other than that particular use, I see no reason for limiting the domain to [0.0, 1.0]. In fact, the entire range covered by double could be permitted (except for NaN, and infinity values).

As these functions will be enhanced with various operators (plus, minus, times, etc.), shall we drop the domain range restriction?
The only immediate problem would be the proposed __reverse__ operator. This can easily be handled by a way more general operation that does any linear remapping of the domain. The proposed __reverse__ operation could than be written as __remapDomain(from, to, scale)__ with parameters 0, 1, -1.

N.B. the reason for ruling out infinity values is that interpolating between a finite domain value and an infinite domain value would be problematic.

**Comment by averbraeck** [comment]
@WJSchakel : what are your thoughts on this?

**Comment by WJSchakel** [comment]
I agree with dropping the limitation. There is one other use-case that will change. Currently the idea of the `sub(double, double)` method is to rescale that to the [0...1] domain. That would then need to become a chained call: `sub(from, to).remapDomain(from, to, 1.0 / (to - from))`. We might opt to instead provide a `normalizeDomain(from, to)` which does exactly that.

**Comment by Peter-Knoppers** [comment]
Limitation dropped.
