### ISSUE TITLE
Interval Comparable problem

### ISSUE THREAD

**Issue by Peter-Knoppers** [averbraeck/djutils#78]
I have two sortedSets that both contain three entries. These have the same keys, but the first key in the first set maps to a different value than the first key in the second set.
The equals method on these sets pronounces the sets equal! I believe this is wrong.

The way the equals method for sorted Set works is like this:
My code has a generated equals method that (if everything else is equal) ends by executing
`         return Objects.equals(this.functions, other.functions);
`
where "functions" is the name of the sortedSet.

Objects.equals os a one-liner:
`        return (a == b) || (a != null && a.equals(b));
`
the call a.equals(b) transfers control to AbstractSet.class line 86
```
    public boolean equals(Object o) {
        if (o == this)
            return true;

        if (!(o instanceof Set))
            return false;
        Collection<?> c = (Collection<?>) o;
        if (c.size() != size())
            return false;
        try {
            return containsAll(c);
        } catch (ClassCastException | NullPointerException unused) {
            return false;
        }
    }
```
The first couple of tests don't resolve the matter, so the hard work needs to be done in the call to containsAll(c). This function looks like this:
```
    public boolean containsAll(Collection<?> c) {
        for (Object e : c)
            if (!contains(e))
                return false;
        return true;
    }

```
For each element in c it checks that this collection contains that as well. The code of contains(e) looks like this:
```
    public boolean contains(Object o) {
        return m.containsKey(o);
    }

```
The code for containsKey looks like this:
```
    public boolean containsKey(Object key) {
        return getEntry(key) != null;
    }

```
As you can see, this only checks that the key yields an entry. The code does __not__ verify that the value of the entry matches.

Is this an error? Or is the equals on a SortedSet (in this case a TreeSet) only supposed to verify that all the keys are there?

In a few seconds I will commit (with a reference to this issue) the code with my failing unit test so you can verify this problem.

**Comment by averbraeck** [comment]
I'll check! Which unit test is it? I can write a quick small test myself.

**Comment by averbraeck** [comment]
@Peter-Knoppers : you probably mean a `SortedMap` rather than a `SortedSet`?

**Comment by averbraeck** [comment]
```java
        SortedMap<Integer, String> s1 = new TreeMap<>();
        s1.put(1,"A");
        s1.put(2,"B");
        SortedMap<Integer, String> s2 = new TreeMap<>();
        s2.put(1,"A");
        s2.put(2,"D");
        System.out.println(s1.equals(s2));
```

result:

```
false
```

**Comment by averbraeck** [comment]
Dus de `SortedMap` checkt zowel de keys als de values.

**Comment by averbraeck** [comment]
The `SortedSet` also checks correctly on the values:

```java
        SortedSet<Integer> s1 = new TreeSet<>();
        s1.add(1);
        s1.add(2);
        SortedSet<Integer> s2 = new TreeSet<>();
        s2.add(1);
        s2.add(3);
        System.out.println(s1.equals(s2));
        System.out.println(Objects.equals(s1, s2));
```

Result: 

```
false
false
```

**Comment by averbraeck** [comment]
Ok -- I see the unit test now. You test:

```java
Concatenation c  = Concatenation.continuousPiecewiseLinear(0.0, 2.0, 0.2, 2.1, 0.5, 1.5, 1.0, 5.5);
Concatenation c2 = Concatenation.continuousPiecewiseLinear(0.0, 3.0, 0.2, 2.1, 0.5, 1.5, 1.0, 5.5);
assertFalse(c.equals(c2));
```

And that does not pass. I will check -- it's probably the implementation of equals(...) for one of the used classes. I'll check.

**Comment by averbraeck** [comment]
The mistake is in `Interval.comparable()`:

```java
    public int compareTo(final Interval<?> other)
    {
        if (this.low < other.low || this.low == other.low && this.lowInclusive && (!other.lowInclusive))
        {
            return -1;
        }
        if (this.low > other.low || this.low == other.low && other.lowInclusive && (!this.lowInclusive))
        {
            return 1;
        }
        return 0;
    }
```

This **only checks the interval, which is indeed equal!** Instead, it should **also** compare the payload. If the payload is not comparable (ordered), a `SortedSet` is not the right way to store these functions, and a `SortedMap` should be used instead, where the `keySet` is the set of intervals (comparable), and the values are the individual `MathFunction` instances that form the `payload` field. The `payload` in that case does not have to be `Comparable`, but just has to implement `equals` when the `values` of the `TreeMap` (or `SortedMap in general) are compared in case the 'keys` are the same.

**Comment by Peter-Knoppers** [comment]
OK. Thus the remedy is to ensure that compareTo will not return 0 for an object that is not totally equal to this. Up till now, the sorting was used to put MathFunctions that might be merged next to one another. I was not aware that the SortedSet (mis)uses the compareTo method to identify identical items. This could have been more clearly documented...

**Comment by averbraeck** [comment]
@Peter-Knoppers : Indeed -- it also took me quite some time to figure this out... But **do ensure** that the behavior whether `compareTo` returns -1 or +1 is completely reproducible (a hashCode compare could already be dangerous since two objects can theoretically have the same hashCode). In the end, it is better not to use a `SortedSet` for this, since the items are, essentially, non-sortable.
