### ISSUE TITLE
`LinearMultiSlider.mapIndexToValue(int)` might do more preparation

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#79]
Currently, the `T LinearMultiSlider.mapIndexToValue(index)` function leaves all the work to the implementation per case. Still, it knows the `doubleValue` of the start index, the `doubleValue` of the end index, so it can interpolate the `doubleValue` of the index. Possibly, it can simplify the implementation to:

```java
abstract T instantiate(double indexAsDouble);
```

**Comment by averbraeck** [comment]
This simplification of the `T LinearMultiSlider.mapIndexToValue(index)` function could have as implication that `LinearMultiSlider<Long>` with high values, e.g. from 10000000000000000 to 10000000000000100 will **not** instantiate the correct `long` value based on an index because of rounding and precision errors. 

@Peter-Knoppers , @WJSchakel : is this a reason to NOT implement this simplification?

**Comment by WJSchakel** [comment]
So if I'm understanding correctly, the slider is at a `long` value, e.g. 10000000000000080, which then gets translated to `double`, and then back to `long` for this specific implementation, which will not be 10000000000000080?

If I'm not understanding correctly, could you interpolate between '0' and 'max minus min', and then add 'min' to it?

**Comment by averbraeck** [comment]
With a `long`, yes. But with a `Length` we do not have a `+` operation, and for a `Time` this `+` operation does not even exist (the intermediate differences become a `Duration`). So, I'm afraid it is very type-specific how the prep work needs to be done. The current situation is that the `mapIndexToValue`method  is completely abstract and gives the `int` thumb values and leaves it to the type-specific implementation how to deal with it. When the type is a djunits type, it might have to handled differently than when it is a `Byte`, `Long`, `BigDecimal`, `DoubleAdder` or `AtomicInteger` (all of these extend `Number`). 

I tend to leave it the way it currently is, and not put code 'inbetween' that would not always work for the specific case, and that introduces rounding errors by definition... Typically the `mapIndexToValue` method is one line of code, but there might be cases where it is much more complicated and you want to use the original 'int' value of the thumb for the calculation. In that case, suppose the `mapIndexToValue` method implements the interpolation on the `double` scale and delegates to an abstract method with the signature: `T instantiate(double value)`. When you need to write the operation using the `int` value, you can still override the `mapIndexToValue` of course, but you would also be forced to implement the (in that case) useless `instantiate` method. 

Therefore, tendency to leave as-is.

**Comment by averbraeck** [comment]
Closed as won't fix.
