### ISSUE TITLE
Update djutils-data project with updated code from opentrafficsim project

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#8]
The code for djutils-data has been updated in opentrafficsim's ots-kpi project. There were still two implementations that diverged. The code in ots-kpi has been updated, and is now ready to be moved from ots-kpi to DJUTILS. This involves:
- `Table`
- `Row`
- `Column`
- `ListTable`
- `CompressedFileWriter` (now in `org.opentrafficsim.base`)
- `TableTester` test code 
- `org.opentrafficsim.kpi.sampling.serialization` package
- `org.opentrafficsim.kpi.sampling.csv` package
- `org.opentrafficsim.kpi.sampling.json` package
- `org.opentrafficsim.kpi.sampling.xml` package

Wouter suggests merging the contents of the latter 3 packages into 1 package. It is 4 classes total that do very similar things.

We have to check and possibly update unit tests, dependencies, package names as well.

**Comment by averbraeck** [comment]
A convenience constructor for `Column` without a unit has been added. The `Column` constructor checks, though, whether DJUNITS values do have a unit:

```java
Throw.when(Value.class.isAssignableFrom(valueType) && (unit == null || unit.length() == 0), 
    IllegalArgumentException.class, "For a DJUNITS value, unit cannot be null or the empty string");
```

**Comment by averbraeck** [comment]
The `Column` class carries out autoboxing for primitive types in its constructor:

```java
this.valueType = valueType.isPrimitive() ? (Class<T>) Primitive.getWrapper(valueType) : valueType;
```

**Comment by averbraeck** [comment]
The `Column` class now tests whether the unit given for a `Scalar` exits for that unit:

```java
    if (Scalar.class.isAssignableFrom(valueType))
    {
        try
        {
            Method valueOfMethod = valueType.getDeclaredMethod("valueOf", String.class);
            valueOfMethod.invoke(null, "1.0" + unit);
        }
        catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException |
                 NoSuchMethodException | SecurityException exception)
        {
            throw new IllegalArgumentException(
                "unit of the Column does not belong to Scalar of type " + valueType.getSimpleName());
        }
    }
```

**Comment by averbraeck** [comment]
An extra interface for the Serializers has been added for types that do not need to be specified further, nor need a unit. To avoid having to implement `IllegalOperationException`, the djunits versions of the `TextSerializer` are taken as the basis, and an extra interface with a convenience `deserialize(text)` method is added. This interface is called `SpecificTextSerializer`. All primitive serializers and the `StringSerializer` implement the `SpecificTextSerializer`. @WJSchakel : is this an option you can approve of?

**Comment by WJSchakel** [comment]
Yes this seems like an appropriate way to expose these serializers outside of the context of tables. The default method takes good care of it.

**Comment by averbraeck** [comment]
Good. I'll implement some more unit tests (already found a few small glitches), and when these are close to 100%, I will merge the branch into main and make a new release. After that, the `Table` classes and the `CompressedFileWriter` can be removed from OTS.

**Comment by WJSchakel** [comment]
Nice. I can make those adjustments on the OTS side, just let me know when OTS is coupled to the new DJUTILS.

**Comment by averbraeck** [comment]
The `StringSerializer` does, in my opinion, a few strange things:

```java
    public String serialize(final String value)
    {
        return value == null ? null : value.toString();
    }

    public String deserialize(final Class<String> type, final String text, final String unit)
    {
        return (text == null || text.isEmpty()) ? null : text;
    }
```

I really do not see why the deserialization of an empty string should return null. In my opinion, that is wrong, since we cannot (de)serialize empty strings in this way. I would change it to:

```java
    public String serialize(final String value)
    {
        return value.toString();
    }

    public String deserialize(final Class<String> type, final String text, final String unit)
    {
        return text;
    }
```

and let the method throw a `NullPointerException` when null strings are offered. @WJSchakel : did I overlook a use-case here?

**Comment by WJSchakel** [comment]
If you have some data including `null` values, serialize that to a file, and read it again, you don't want to end up with `""`'s. This for example happens with `FilterDataType`'s in trajectories. For each `Trajectory`, such information is only stored on the first row of a trajectory.

CSV:
```
traj#,linkId,laneId&dir,gtuId,t,x,v,a,origin
1,OriginLane-drop,Lane 3,1,3.0,112.5678,39.18096,0.0,Origin
1,OriginLane-drop,Lane 3,1,3.1,116.48589,39.18096,0.0,
1,OriginLane-drop,Lane 3,1,3.2,120.40399,39.18096,0.0,
```

JSON:
```
  "data": [
    [{"0":"1"},{"1":"OriginLane-drop"},{"2":"Lane 3"},{"3":"1"},{"4":"3.0"},{"5":"112.5678"},{"6":"39.18096"},{"7":"0.0"},{"8":"Origin"}],
    [{"0":"1"},{"1":"OriginLane-drop"},{"2":"Lane 3"},{"3":"1"},{"4":"3.1"},{"5":"116.48589"},{"6":"39.18096"},{"7":"0.0"},{"8":null}],
    [{"0":"1"},{"1":"OriginLane-drop"},{"2":"Lane 3"},{"3":"1"},{"4":"3.2"},{"5":"120.40399"},{"6":"39.18096"},{"7":"0.0"},{"8":null}],
```

XML (note the empty tags at column 8, explicitly indicating `null`):
```
    <row index="0">
      <value nr="0" content="1"/>
      <value nr="1" content="OriginLane-drop"/>
      <value nr="2" content="Lane 3"/>
      <value nr="3" content="1"/>
      <value nr="4" content="3.0"/>
      <value nr="5" content="112.5678"/>
      <value nr="6" content="39.18096"/>
      <value nr="7" content="0.0"/>
      <value nr="8" content="Origin"/>
    </row>
    <row index="1">
      <value nr="0" content="1"/>
      <value nr="1" content="OriginLane-drop"/>
      <value nr="2" content="Lane 3"/>
      <value nr="3" content="1"/>
      <value nr="4" content="3.1"/>
      <value nr="5" content="116.48589"/>
      <value nr="6" content="39.18096"/>
      <value nr="7" content="0.0"/>
      <value nr="8"/>
    </row>
    <row index="2">
      <value nr="0" content="1"/>
      <value nr="1" content="OriginLane-drop"/>
      <value nr="2" content="Lane 3"/>
      <value nr="3" content="1"/>
      <value nr="4" content="3.2"/>
      <value nr="5" content="120.40399"/>
      <value nr="6" content="39.18096"/>
      <value nr="7" content="0.0"/>
      <value nr="8"/>
    </row>
```

**Comment by WJSchakel** [comment]
I'm not sure this goes right when reading CSV.

**Comment by averbraeck** [comment]
Hmmm. But that would also hold for doubles, integers, Scalars, etc., where we DO throw a `NullPointerException` when the (de)serializer gets a null argument. Yet, these columns could also be empty. IMHO, either all columns can handle null for being empty (which is a good use-case), or none. My suggestion would be to add similar code to **all** serializers, and to document this as intended behavior in the Javadoc, where this is not mentioned now.

**Comment by averbraeck** [comment]
> I'm not sure this goes right when reading CSV. I don't think it has an explicit null option.

You can for sure skip an argument in a CSV by doing ',,' When I build unit tests for this, we will see where it breaks... I will for sure include it in unit tests for all formats.

**Comment by averbraeck** [comment]
@WJSchakel : what about the `text.isEmpty()` in deserializing a String? Now we cannot distinguish between no information and an explicit empty string. I do not see a way out for this, though.

**Comment by WJSchakel** [comment]
> > I'm not sure this goes right when reading CSV. I don't think it has an explicit null option.
> 
> You can for sure skip an argument in a CSV by doing ',,' When I build unit tests for this, we will see where it breaks... I will for sure include it in unit tests for all formats.

Siegmar says this is not possible with FastCSV: https://github.com/osiegmar/FastCSV/issues/58

But I would say ',,' is semantically different from ',"",',

**Comment by averbraeck** [comment]
Yes, it is different. But we can probably not make the distinction. I will build some tests for this. What about the remark about analogous null values for all other (de)serialization types?

**Comment by WJSchakel** [comment]
> @WJSchakel : what about the `text.isEmpty()` in deserializing a String? Now we cannot distinguish between no information and an explicit empty string. I do not see a way out for this, though.

Hmm yes, that does not seem right. We cannot store `""`, and read it as such.

Only thing I can think of is to just have some escape string that is then not allowed to be in the data, like `"@null"`. But, we could couple that to a different data type `NullableString`.
- `String`: can be anything but `null`.
- `NullableString`: can be anything but `"@null"`.

**Comment by WJSchakel** [comment]
> Yes, it is different. But we can probably not make the distinction. I will build some tests for this. What about the remark about analogous null values for all other (de)serialization types?

XML and JSON have ways for this, so that should work. I would really prefer the ability to have `null` values.

**Comment by averbraeck** [comment]
>  have some escape string that is then not allowed to be in the data, like "@null"

Each escape string could be a legitimate String value in a Table... I am against having a 'magic string' that you cannot use in a table. Only String has this problem, by the way. For Double, Float, DoubleScalar, etc. the value could even be an explicit 'null' string as the serialized value. This only goes wrong for String itself....

**Comment by averbraeck** [comment]
> I would really prefer the ability to have null values.

I will build this in for all TestSerializers, and make it part of the contract in the interface Javadoc.

**Comment by WJSchakel** [comment]
What about the ASCII value for null? I guess that is also a valid String on its own.

**Comment by averbraeck** [comment]
> What about the ASCII value for null? I guess that is also a valid String on its own.

Yes, it is...

**Comment by WJSchakel** [comment]
Then I only see the option that we can specify how to treat ',,' in CsvData, per `Column` probably.

**Comment by averbraeck** [comment]
> Then I only see the option that we can specify how to treat ',,' in CsvData, per Column probably, or overall.

I will see in the unit tests and the `DataDemo` class how far I get, and possibly park it as a new issue. For now, I am allowing null values for ALL (de)serialized types to denote an unspecified value, both for the `serialize` and for the `deserialize` method.

**Comment by averbraeck** [comment]
In a sense, the `Optional` class in code is meant for these use-cases. See https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html. Still does not solve what to store in the csv-file, though...

**Comment by WJSchakel** [comment]
What if we just always put a character in front of it?

`"a" -> ',1a,' -> "a"`
`null -> ',0null,' -> null`
`"null" -> `,1null,` -> "null"`

**Comment by averbraeck** [comment]
Yuck. This means that the csv files and other files are unusable outside the Java context. Defeats the purpose of making these files in the first place.

**Comment by WJSchakel** [comment]
Ok, one more attempt: we add a column (only in the .csv file) in front of each `String` column, which contains 1's and 0's, where 1 indicates the String in the next column is indeed a string (even when ',,' which is `""`), and where 0 indicates that the next column is `null` and should be empty ',,'.

Could be read fine by Excel for example. And in the .csv itself, unique column ids are not required.

**Comment by averbraeck** [comment]
Under what circumstances would handling an empty string be different from handling a non-specified string? I cannot think of an example where these would really lead to a difference. When I get back a null from deserializing a String, I know the value was not specified, or the string that was serialized had length zero. In a specific context, I would always know what to do, and there would be no difference in handling either case. (at least in all examples I could come up with). So maybe we are trying to solve a non-problem.

Most important: all values CAN be null now in (de)serialization, and WILL lead to empty column values in any type of file we read or write in djutils-data.

**Comment by averbraeck** [comment]
Null values testing (and empty string testing) work fine now in all columns. Serializing and deserializing works for csv-files and is about to be tested for tsv, json and xml files.

**Comment by averbraeck** [comment]
@WJSchakel : One addition that was made in OTS is that a column can have a unit. But the contract for that feature is not clear. Serializing and deserializing if Scalars only works fine when the column is in the base unit. When a Length column is, e.g., in km, and a value in meters is offered, `deserialize(serioalize(length))` does not return the same value. There is little information in the `Column` class about what should happen, but the `getUnit()` method has Javadoc stating: "Data is written an read using this unit". Apparently, this is not true in the further implementation... What is the exact intention? And where might it go wrong?

**Comment by WJSchakel** [comment]
I see your point. In OTS there were classes `TableCsvWriter` and `TableCsvReader`. To these you could add your custom (de)serializers (they were named (un)marshallers). Because of this, you had the option to store Scalars with their individual units, which would only make sense with a column without unit (e.g. "1.234 m"). Or using another (un)marshaller, the column has a unit and you store the values in that unit without the unit (e.g. "0.0123"). The way it is now in djutils, the (de)serializer is statically resolved from the type.

What we could do is also serialize using a unit. If there is no unit, store with unit of the Scalar. If there is a unit, store in that unit. This will probably also require a simpler version the `serialize` method:

```
String serialize(T value, String unit);

default String serialize(T value)
{
    return serialize(value, "");
}
```

This is the first place where having a `Unit` over a `String` would really be better...

**Comment by WJSchakel** [comment]
If the `Unit` can be resolved from the `String` version of the unit, the data reader can do that once, and forward it:

```
String serialize(T value, Unit<?> unit);

default String serialize(T value)
{
    return serialize(value, null);
}
```

**Comment by averbraeck** [comment]
It already does that, as far as I can see. I think the problem lies with the conversion that is done only on serializing, but not on deserializing. Following up on your comments above with an example:

When a Length column does **NOT** have a unit, Lengths 1 km, 2 mm and 3 m are stored as: "1.0 km", "2.0 mm" and "3.0 m" in the rows of the table.

When a Length column **DOES** have a unit, conversions take place on serializing to convert the scalar to the unit of the table column. 
- When the Column has as unit 'm', the Lengths 1 km, 2 mm and 3 m are stored as: "1000.0", "0.002" and "3.0" in the rows of the table. Note that deserializing will give back 1000.0 m, 0.002 m, and 3.0 m. So the original units are lost.
- When the Column has as unit 'mm', the Lengths 1 km, 2 mm and 3 m are stored as: "1000000.0", "2.0" and "0.003" in the rows of the table. Note that deserializing will give back 1000000.0 mm, 2.0 mm, and 3000 mm. So the original units are lost.

In my opinion, that would be the expected behavior. I think the code is already pretty close to this, but fails to do the scalar conversion to the column unit at serializing.

**Comment by averbraeck** [comment]
And of course the above is dependent on the Locale. If you agree that this is the intended behavior, I will use the above comments as an example in the Javadoc for Column and the scalar serializers, and also include it in the doc files.

**Comment by WJSchakel** [comment]
> When a Length column does **NOT** have a unit, Lengths 1 km, 2 mm and 3 m are stored as: "1.0 km", "2.0 mm" and "3.0 m" in the rows of the table.

Are you sure? The current code in the branch for `DoubleScalarSerializer` has the code below. Or did you already update this top include the unit?

```
    public String serialize(final S value)
    {
        return value == null ? null : String.valueOf(value.doubleValue());
    }
```

Anyway, the following code can serialize to a column unit. Of course, the `Unit` should be derived once for a column, and not for every call to `serialize`. This would require the method signature as in my previous post.

```
    public static <T> void main(final String[] args)
    {
        String unitString = "km";
        AbstractDoubleScalar<?, ?> scalar = Length.ONE;

        double value = serialize(scalar, unitString);
        System.out.println("The value is " + value + unitString); // The value is 0.001km
    }

    private static <T extends AbstractDoubleScalar<U, T>,
            U extends Unit<U>> double serialize(final AbstractDoubleScalar<?, ?> scalar, final String unitString)
    {
        U unit = (U) scalar.getDisplayUnit().getQuantity().getUnitByAbbreviation(unitString);
        return ((T) scalar).getInUnit(unit);
    }
```

**Comment by WJSchakel** [comment]
> In my opinion, that would be the expected behavior. I think the code is already pretty close to this, but fails to do the scalar conversion to the column unit at serializing.

Agreed.

**Comment by averbraeck** [comment]
> public String serialize(final S value)

The problem is that the standard serialize() method does not have a unit. So it can only output a string with the value in the SI or base unit. Creating the required behavior would require the `serialize()` method also to have a unit to which it converts the value. When unit is blank or null, it can convert to a String with the unit; when it is not null, it converts the value to that displayUnit and creates a string with just the value. The static methods you mention above would then be able to use the serializer directly. 

It would be handy for this if the `Column` has a `getUnit()` method that can return a true unit, in addition to the current method that could be renamed to `getUnitString()`.

**Comment by WJSchakel** [comment]
Knowing the `Unit<?>`, would it make sense to change the deserialize method to this?

`public S deserialize(final Class<S> type, final String text, final Unit<?> unit)`

I guess it would speed up deserialization, as the current `valueOf()` approach will cause the Scalar to have to figure out the unit for every value deserialized.

**Comment by averbraeck** [comment]
This is not needed. `serialize` with a unit in the column only stores a number in the cvs or other file.

**Comment by averbraeck** [comment]
A JSON example:

```json
{
  "table": {
    "id": "engineTemperatureData",
    "description": "engine temperature samples",
    "class": "org.djutils.data.ListTable",
    "columns": [
      {
        "nr": 0,
        "id": "timeStamp",
        "description": "time rounded to nearest second",
        "type": "org.djunits.value.vdouble.scalar.Time",
        "unit": "s"
      },
      {
        "nr": 1,
        "id": "temperature",
        "description": "engine temperature in Celcius",
        "type": "org.djunits.value.vdouble.scalar.AbsoluteTemperature",
        "unit": "K"
      },
      {
        "nr": 2,
        "id": "remark",
        "description": "remark",
        "type": "java.lang.String",
        "unit": ""
      }
    ]
  },
  "data": [
    [{"0":"600.0"},{"1":"291.15"},{"2":"starting engine"}],
    [{"0":"660.0"},{"1":"301.65"},{"2":"leaving parking lot"}]
  ]
}
```

**Comment by averbraeck** [comment]
Indeed for **deserializing**, we get something like:

```java
Duration d = Duration.of(text, column.getUnit());
```

But for **serializing**, the serializer has no clue what to do. It has neither a unit to convert to, nor  a column from which it can retrieve the unit...

**Comment by WJSchakel** [comment]
Whoops, I meant **serialize**:

`String serialize(T value, Unit<?> unit);`

**Comment by averbraeck** [comment]
Ok, then we agree 100% I think. I will make the implementation.

**Comment by averbraeck** [comment]
We do have to specify possible precision loss in the Javadoc, though, when a Column has a unit. For this I already created a unit test that stores pi miles in a Length column with km as the column unit.

**Comment by WJSchakel** [comment]
Ok. One more consideration: the unit should be able to be used not as a `Unit<?>`. What if someone wants to store "directions over an intersection following a standard coding" with the standard coding being given in the unit?

Column unit: "Dutch NEN 3021"
Values: 3.1, 3.2, 41.1

Column unit: "EU NEN 5012"
Values: 112, 133, 83

But, this would be for a `Column` that does *not* have a DJUNITS Scalar type, i.e. a different (de)serializer. So, the column should remember the unit as `String`, and as a utility for DJUNITS Scalar types, be able to give it as `Unit<?>` with possible exception if the type is not correct / the string is not a valid unit.

**Comment by WJSchakel** [comment]
Open issue (I think for another issue #): define custom (de)serializers for any type.

**Comment by WJSchakel** [comment]
> Open issue (I think for another issue #): define custom (de)serializers for any type.

My idea would be to be able to add custom (de)serializers to `Column`s.

**Comment by averbraeck** [comment]
Hmmm. If you take that one step further, and **always** store the used serializer in every column, and also in the metadata in the table, so the deserialization uses the right (de)serializer. For Scalars, the serializer will be instantiated with the unit given in the column, we also solved several other parts of the implementation that are not 100% elegant. Indeed a new issue. I  will first fix this code, so it works as intended. Then we can think about changes and extensions.

**Comment by WJSchakel** [comment]
> and also in the metadata in the table, so the deserialization uses the right (de)serializer.
When I realized this, I removed my comment about adding it to the `Column` as I wasn't sure there was merit in the idea. But I guess it is both elegant and flexible.

**Comment by averbraeck** [comment]
See issue #9

**Comment by averbraeck** [comment]
For now, there is a stable table project where columns with units (de)serialize in a consistent way. This has been tested in csv, tsv, json and xml files. Null values in rows have also been tested for all serializers and file formats. Test coverage is 96%. 

I will merge the branch with the main branch and make a release of this version.
