### ISSUE TITLE
Window maximize not caught in resize event

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#80]
When a window with MultiSliders is maximized, the track size is not recalculated, and labels are not redrawn. Apparently, maximizing is treated differently from resizing.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a component listener to AbstractMultiSlider to recalculate track size and redraw labels when the window is maximized or resized.

You can review changes in this commit: https://github.com/mnmnk43434/averbraeck-djutils-80/commit/caf3d22278164c56420eaad1f6551a3e734d77b3.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by averbraeck** [comment]
There was already a `ComponentListener.componentResized(...)` present. Catching a maximize event as suggested above does not work -- these only exist on a `JFrame` or AWT `Frame`, not on a `JPanel`. The solution involved a small hack that forces a complete redraw: `setUI(getUI())`:

```java
// listen to resize events to (re)set the track width or height
addComponentListener(new ComponentAdapter()
{
    @Override
    public void componentResized(final ComponentEvent e)
    {
        super.componentResized(e);
        AbstractMultiSlider.this.setUI(getUI());
        calculateTrackSize();
        AbstractMultiSlider.this.dispatcherPane.revalidate();
        AbstractMultiSlider.this.labelPanel.revalidate();
        AbstractMultiSlider.this.labelPanel.repaint();
    }
});
```

which is a small adaptation from the already existing code.
