### ISSUE TITLE
Knots reporting enum

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils#84]
`MathFunction` may or may have knots, and may or may not be able to report them, and may or may not be able to approximate them numerically. In order to know this about a `MathFunction`, it should return for `getKnotReport(Interval)` an enum `KnotReport` having values:

- `NONE`; it is known there are no knots (an empty set)
- `KNOWN_FINITE`; all knots are exactly known (a set, can still be empty)
- `KNOWN_INFINITE`; all knots are exactly known (exception will be thrown)
- `UNKNOWN`; there is no way of knowing (exception will be thrown)

Between braces it is indicated what `getKnots(Interval)` on the same interval is expected to return or throw.

`KnotReport` has a method `isFinite()` which returns `true` for `NONE` and `KNOWN_FINITE`.

**Comment by Peter-Knoppers** [comment]
Implemented.
